version: "3.9"

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - media-stack-network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./sonarr/config:/config
      - ${TV_PATH}:/tv
      - ${DOWNLOADS_PATH}:/downloads
    ports:
      - "${SONARR_PORT}:8989"
    restart: unless-stopped

networks:
  media-stack-network:
    external: true

