version: "3.9"

services:
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    networks:
      - media-stack-network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - "${RADARR_PORT}:7878"
    volumes:
      - ./radarr/config:/config
      - ${MOVIES_PATH}:/movies
      - ${DOWNLOADS_PATH}:/downloads
    restart: unless-stopped

networks:
  media-stack-network:
    external: true

